export PROJECT = taskscheduler
IMPORT_PATH := github.com/shahzadhaider7/${PROJECT}

# all non-windows environments
ROOT := $(shell pwd)

DEV_IMAGE := ${PROJECT}_dev

DOCKRUN := docker run --rm \
	-v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
	${DEV_IMAGE}

DOCKTEST := docker run --rm \
    -v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
    --link task-scheduler-mongo-db:task-scheduler-mongo-db \
    --link task-scheduler-mysql-db:task-scheduler-mysql-db \
    ${DEV_IMAGE}